# Setup
title:        "Fairness in Networks"
tagline:      A tutorial at KDD 2021
baseurl:      "/kdd-2021-network-fairness-tutorial/"
paginate:     1
locale:       "en"
exclude:      [ "README.md", "Gemfile.lock", "Gemfile", "jekyll-cayman-theme.gemspec" ]

# About/contact
author:
  name:       Sorelle Friedler, Carlos Scheidegger, Suresh Venkatasubramanian
  url:        https://algofairness.github.io/kdd-2021-network-fairness-tutorial/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
